default: &default
  adapter: postgresql
  encoding: unicode
  username: masteruser
  password: simplesimple
  host: localhost
  port: 5432

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: zero_waste_development

test:
  <<: *default
  database: zero_waste_test

staging:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

production:
  <<: *default
  # database: zero_waste_production
  # username: zero_waste
  # password: <%= ENV['ZERO_WASTE_DATABASE_PASSWORD'] %>
